# Site settings
title:       Henrique Silvério
email:       hello@henriquesilver.io
author:      Henrique Silvério
description: "Um blog sobre desenvolvimento Web / Front-End."
baseurl:     ""
url:         "http://blog.henriquesilver.io"

# Google analytics
google_analytics: UA-38436089-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: henriquesilverio

# Social icons
show_social_icons: true
github_username: HenriqueSilverio
stackoverflow_id:
twitter_username: RikeSilverio
google_plus_id:
linkedin_username: henriquesilverio
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:categories/:title
paginate:     5
sass:
  compressed: true
gems:
  - jekyll-sitemap
